const express = require('express');
const server = express();
server.use(express.json());

// ESTA APLICAÇÃO DEVERÁ CRIAR UMA API COM OS SEGUINTES METODOS

// CREATE PROJECTS
// READ PROJECTS
// READBYID PROJECTS
// DELETE PROJECTS

// DEVERÁ CONTER TAMBEM MIDDLEWARES DE TRATAR ERROS
